### ISSUE TITLE
ValueError: Cannot insert None into a tag.

### ISSUE THREAD

**Issue by otomay** [Nata4n/passeidireto-cli#1]
* python 3.10.11 / windows 11

it throws this error when trying to do the basic usage

_python main.py [-u URL] [-o OUTPUT]_
`ValueError: Cannot insert None into a tag.`

also it does not work on linux. maybe put windows in pre-requisites

thanksss

![image](https://github.com/natanrce/passeidireto-cli/assets/54224340/229d0302-eea8-4946-8687-ea15dcc92f30)
![image](https://github.com/natanrce/passeidireto-cli/assets/54224340/4e7fbcd5-6503-4299-a033-efb9777b0609)

**Comment by Resonosity** [comment]
Getting the same issue. Installed passeidireto-cli on both Ubuntu 20.04 and Windows 11 23H2 with Python 3.13.1, and am hitting the same road block. 

Ubuntu 20.04:
`/home/<User>/.local/lib/python3.8/site-packages/bs4/builder/__init__.py:545:` XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.

  warnings.warn(
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!

  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):

  File "main.py", line 29, in <module>
    app.run()

  File "/mnt/c/Users/<User>/passeidireto-cli/src/app.py", line 26, in run
    asyncio.run(self.download_material())

  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()

  File "/mnt/c/Users/<User>/passeidireto-cli/src/app.py", line 57, in download_material
    styled_content = list(map(callback, result))

  File "/mnt/c/Users/<User>/passeidireto-cli/src/app.py", line 54, in callback
    return self.passei_direto_service.get_css(x, file_url)

  File "/mnt/c/Users/<User>/passeidireto-cli/src/services/passeidireto.py", line 58, in get_css
    body_div.insert(0, content_div)

  File "/home/<User>/.local/lib/python3.8/site-packages/bs4/element.py", line 417, in insert
    raise ValueError("Cannot insert None into a tag.")

ValueError: Cannot insert None into a `tag.`

Windows 11 23H2:
`C:\Users\<User>\passeidireto-cli\src\services\passeidireto.py:29: XMLParsedAsHTMLWarning: It looks like you're using an HTML parser to parse an XML document.

Assuming this really is an XML document, what you're doing might work, but you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the Python package 'lxml' installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.

If you want or need to use an HTML parser on this document, you can make this warning go away by filtering it. To do that, run this code before calling the BeautifulSoup constructor:

    from bs4 import XMLParsedAsHTMLWarning
    import warnings

    warnings.filterwarnings("ignore", category=XMLParsedAsHTMLWarning)

  soup = BeautifulSoup(html_content, features='html5lib')
Traceback (most recent call last):
  File "C:\Users\<User>\passeidireto-cli\src\main.py", line 29, in <module>
    app.run()
    ~~~~~~~^^
  File "C:\Users\<User>\passeidireto-cli\src\app.py", line 26, in run
    asyncio.run(self.download_material())
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\<User>\passeidireto-cli\src\app.py", line 57, in download_material
    styled_content = list(map(callback, result))
  File "C:\Users\<User>\passeidireto-cli\src\app.py", line 54, in callback
    return self.passei_direto_service.get_css(x, file_url)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\<User>\passeidireto-cli\src\services\passeidireto.py", line 58, in get_css
    body_div.insert(0, content_div)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python313\Lib\site-packages\bs4\element.py", line 1931, in insert
    inserted.extend(self._insert(position, new_child))
                    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python313\Lib\site-packages\bs4\element.py", line 1937, in _insert
    raise ValueError("Cannot insert None into a tag.")
ValueError: Cannot insert None into a tag.`

@natanrce , any thoughts on this?
